platform :ios, '13.0'

target 'Any_competition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	# Firebase Pods
    pod "KRTournamentView"

	 # Firebase Pods
    pod 'Firebase'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'

	# Lottiefiles
    pod 'lottie-ios'

end