# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Any_competition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	# Firebase Pods
    pod "KRTournamentView"

	 # Firebase Pods
    pod 'Firebase'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'

	#Lottiefiles
  pod 'lottie-ios'
    
  # Pods for Any_competition

  target 'Any_competitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Any_competitionUITests' do
    # Pods for testing
  end

end
